site_name: CDE‑AWP Lifecycle Framework
site_url: https://kiiiiit.github.io/cde-awp-lifecycle-framework-cre/
docs_dir: .
theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs.link
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
nav:
  - Home: README.md
  - Framework: Framework_CDE-AWP_RealEstate.md
  - Technical Doc: Technical_Documentation.md
  - OnePager: OnePager_CDE-AWP_Framework.md
  - Sections:
      - 01 Gates: 01_Gates_Methodology.md
      - 02 CDE Data Model: 02_CDE_Data_Model.md
      - 03 ISO 81346: 03_Classification_ISO81346.md
      - 04 AWP Packaging: 04_AWP_Packaging.md
      - 05 Procurement: 05_Procurement_Readiness.md
      - 06 System Readiness & Cx: 06_System_Readiness_and_Cx.md
      - 07 O&M As‑Maintained: 07_OandM_AsMaintained.md
      - 08 KPI & Reporting: 08_KPI_and_Reporting.md
      - 09 Roles & Policies: 09_Roles_RACI_and_Policies.md
      - 10 CRE Addendum: 10_Commercial_RealEstate_Addendum.md
  - Extras:
      - Formats & Acceptance: Formats_and_Acceptance.md
      - Lifecycle Map & Gates: LC_Map_and_Gates.md
      - AWP & Execution: AWP_and_Execution_Planning.md
      - System Readiness Details: System_Readiness_and_Cx_Details.md
      - O&M for CRE: OandM_Commercial_RealEstate.md
      - KPI Details: KPI_and_Reporting_Details.md
      - Roles: Roles_and_Responsibility.md
      - Templates & Forms: Ready_Templates_and_Forms.md
      - Mini Guide: Mini_Implementation_Guide.md
      - SUJCO Scheme: docs/SUJCO.md
      - AWP Flow: docs/AWP_Flow.md
      - Cx Matrix: docs/Cx_Matrix.md
      - RACI: docs/RACI.md
      - BI Integration: docs/BI_Integration.md
      - API: docs/API.md
      - Data Tools: docs/Data_Tools.md
      - Reports: docs/Reports.md
      - Roadmap: ROADMAP.md
