pilot:
  project_id: CRE-PILOT-01
  asset_type: "Business Center"
  focus_systems: [HVAC, Electrical, BMS]
  critical_paths: [core, facades, HVAC, lifts, BMS]
  tenants_fitout: true
  schedules:
    reports_weekly: true
  kpi:
    - SCH_ONTIME_AWP
    - CX_PASS_FIRST
    - REWORK_INDEX
    - OPEX_ENERGY_INT
