name: Validate data and generate reports
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install jsonschema pyyaml jinja2
      - run: python tools/validate.py
      - run: python tools/check_gate_inputs.py
      - run: python tools/agg_kpi.py
      - run: python tools/calc_readiness.py
      - run: python tools/gen_weekly_report.py
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/out
